services:
  keycloak:
    image: keycloak-themed
    build: .
    ports:
      - 8080:8080
      - 8180:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
